import { ThemeProvider } from "@/contex/theme-provider";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const urbanist = Urbanist({ subsets: ["latin"] });
// const open_sans = Open_Sans({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-open_sans",
// });



export const metadata: Metadata = {
  title: "Resume.AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("bg-background",  urbanist.className)}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster/>
          </ThemeProvider>
      </body>
    </html>
  );
}
